### ISSUE TITLE
Mud does not register when using this with Earth2Java

### ISSUE THREAD

**Issue by TheIrishStud** [badasintended/wthit#61] opened 2021-08-18 20:33 UTC
Reloaded my 1.17.1 home world seed and found mud nearby while testing out Earth2Java with WTHIT but it didn't register like some of the newly added mobs after combining this with Earth2Java. I'm using one of the most recent updates for fabric to use sodium 0.3.0 and I already reported the bug to the Earth2Java mod creator before coming here. Just the 1st small bug I've found so far. It can still be identified when using F3 though so it's not that immersion breaking. I hope this helps! ^_^

https://www.curseforge.com/minecraft/mc-mods/earth2java-fabric

**Comment by deirn** [comment] 2021-08-19 06:26
Is mud a fluid by chance? if so you need to enable fluid tooltip on the Waila Core config

**Comment by deirn** [comment] 2021-09-20 04:32
Closing this, it's not a bug. Mud is a fluid, so you need to enable the fluid tooltip.

**Closed by deirn** 2021-09-20 04:32 UTC
Labels: bug, fabric
