### ISSUE TITLE
Crashing Client Randomly

### ISSUE THREAD

**Issue by cccs16** [badasintended/wthit#148] opened 2022-07-03 02:48 UTC
### Describe the issue

Nothing too explanatory, but I will say I am running 1.19 with Fabric. It has been happening with other mods too. 

### Log output

https://crashy.net/mtmNekSmx0FaJ0IWIOSo

### Additional context

```
#---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 7/2/22, 10:43 PM
Description: Unexpected error

java.lang.IllegalStateException
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.4)
	at com.google.common.base.Preconditions.checkState(Preconditions.java:486)
	at mcp.mobius.waila.gui.hud.TooltipRenderer.beginBuild(TooltipRenderer.java:87)
	at mcp.mobius.waila.gui.hud.TooltipHandler.tick(TooltipHandler.java:81)
	at mcp.mobius.waila.WailaClient.onClientTick(WailaClient.java:44)
	at mcp.mobius.waila.fabric.FabricWailaClient.lambda$onInitializeClient$0(FabricWailaClient.java:21)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
	at net.minecraft.client.MinecraftClient.handler$zmd000$onEndTick(MinecraftClient:6390)
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1869)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1101)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:734)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.client.MinecraftClient.modify$bkc000$atTheEndOfSecondCatchBeforePrintingCrashReport(MinecraftClient:10939)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:761)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.client.MinecraftClient.modify$bkc000$atTheEndOfSecondCatchBeforePrintingCrashReport(MinecraftClient:10939)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:761)
	at net.minecraft.client.main.Main.main(Main:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.google.common.base.Preconditions.checkState(Preconditions.java:486)
	at mcp.mobius.waila.gui.hud.TooltipRenderer.beginBuild(TooltipRenderer.java:87)
	at mcp.mobius.waila.gui.hud.TooltipHandler.tick(TooltipHandler.java:81)
	at mcp.mobius.waila.WailaClient.onClientTick(WailaClient.java:44)
	at mcp.mobius.waila.fabric.FabricWailaClient.lambda$onInitializeClient$0(FabricWailaClient.java:21)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
	at net.minecraft.class_310.handler$zmd000$onEndTick(class_310.java:6390)

-- Affected level --
Details:
	All players: 1 total; [class_746['DJLinx'/31079, l='ClientLevel', x=-412.70, y=62.00, z=-903.70]]
	Chunk stats: 1024, 48
	Level dimension: minecraft:overworld
	Level spawn location: World: (-288,64,-480), Section: (at 0,0,0 in -18,4,-30; chunk contains blocks -288,-64,-480 to -273,319,-465), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 57888 game time, 306593 day time
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2288)
	at net.minecraft.class_310.method_1514(class_310.java:758)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$bkc000$atTheEndOfSecondCatchBeforePrintingCrashReport(class_310.java:10939)
	at net.minecraft.class_310.method_1514(class_310.java:761)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$bkc000$atTheEndOfSecondCatchBeforePrintingCrashReport(class_310.java:10939)
	at net.minecraft.class_310.method_1514(class_310.java:761)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, lambdabettergrass/default, EmbellishedStone-1.19-1.0.0.zip, Better-Leaves-7.1-1.19+.zip, cullleaves/smartleaves, Clarity_1.19.zip

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 290544512 bytes (277 MiB) / 1409286144 bytes (1344 MiB) up to 17951621120 bytes (17120 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 79 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Radeon RX 580 Series
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x67df
	Graphics card #0 versionInfo: DriverVersion=30.0.15021.11005
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 37539.80
	Virtual memory used (MB): 23982.13
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 86.97
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx17120m -Xms256m
	Fabric Mods: 
		advancementplaques: Advancement Plaques 1.4.5
		appleskin: AppleSkin 2.4.0+mc1.19
		badpackets: Bad Packets 0.1.2
		betterf3: BetterF3 1.3.1
		blur: Blur (Fabric) 2.6.0
			midnightlib: MidnightLib 0.5.2
			satin: Satin 1.8.0
		cloth-config: Cloth Config v6 7.0.72
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 9.0.0+3
		cullleaves: Cull Leaves 2.3.4
		dashloader: DashLoader 4.0.0+1.19
			com_github_luben_zstd-jni: zstd-jni 1.5.2-2
			dev_quantumfusion_hyphen: Hyphen 0.2.2
			dev_quantumfusion_taski: Taski 1.1.0
		debugify: Debugify 2.2.0
			com_github_llamalad7_mixinextras: mixinextras 0.0.11
		durabilityviewer: Giselbaers Durability Viewer 1.19-fabric0.53.3-1.10.3
			crowdin-translate: CrowdinTranslate 1.4+1.19
			gbfabrictools: GBfabrictools 1.3.4+1.19
		dynamicfps: Dynamic FPS 2.2.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		enhancedblockentities: Enhanced Block Entities 0.7.1+1.19
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
			spruceui: SpruceUI 4.0.0+1.19
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		fabric: Fabric API 0.57.0+1.19
			fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.14+b2a4a624a9
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f40a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.6+f71b366fa9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.2+0d55f585a9
			fabric-commands-v0: Fabric Commands (v0) 0.2.23+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.27+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.0+07df213ea9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.1+a680b9b4a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.28+a6d2f785a9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.25+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.4+767db26ea9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.25+9ff28f40a9
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.18+9ff28f40a9
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b3a9
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc738a9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.0+03a4e568a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.3+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.10+33fbc738a9
			fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f40a9
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.27+7fe97409a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.14+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.7+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.17+23c4cfefa9
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f40a9
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.9+1f92344ea9
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b3a9
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b3a9
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.5+a6d2f785a9
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.24+f05effafa9
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.6+9ff28f40a9
			fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f40a9
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.9+e62f51a3a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
		fabricloader: Fabric Loader 0.14.8
		fallingleaves: Falling Leaves 1.12.1+1.19
		forgeconfigapiport: Forge Config API Port 4.0.0
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		iceberg: Iceberg 1.0.38
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 11.0.0.206
		lambdabettergrass: LambdaBetterGrass 1.3.0+1.19
		lambdynlights: LambDynamicLights 2.1.2+1.19
			pride: Pride Lib 1.1.2+1.19
		lazydfu: LazyDFU 0.1.3
		lithium: Lithium 0.8.0
		minecraft: Minecraft 1.19
		modmenu: Mod Menu 4.0.0
		mousetweaks: Mouse Tweaks 2.22
		notenoughcrashes: Not Enough Crashes 4.1.6+1.19
		paintings: Paintings++ 10.0.0.0
		phosphor: Phosphor 0.8.1
		skinlayers: 3d Skin Layers 1.4.7-mc1.19
		sodium: Sodium 0.4.2+build.16
			org_joml_joml: joml 1.10.4
		transparent: Transparent 5.1.0
		wthit: wthit 5.5.0
	Launched Version: fabric-loader-0.14.8-1.19
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Radeon RX 580 Series GL version 3.2.14800 Core Profile Forward-Compatible Context 22.5.1 30.0.15021.11005, ATI Technologies Inc.
	Window size: 3840x2131
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, lambdabettergrass/default, file/EmbellishedStone-1.19-1.0.0.zip, file/Better-Leaves-7.1-1.19+.zip, cullleaves/smartleaves, file/Clarity_1.19.zip
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz
	Client Crashes Since Restart: 3
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader), wthit (wthit), Not Enough Crashes (notenoughcrashes), Fabric Lifecycle Events (v1) (fabric-lifecycle-events-v1)
```

**Comment by deirn** [comment] 2022-07-03 03:49
Duplicate of #147. Should already be fixed in 5.5.1.

**Closed as not planned by deirn** 2022-07-03 03:49 UTC
Labels: bug, fabric
