### ISSUE TITLE
Unusual crash when looking at blocks: `Cannot invoke "ToolTier.isEqualTo(ToolTier)" because the return value of "ToolTier.get(Tier)" is null`

### ISSUE THREAD

**Issue by unilock** [badasintended/wthit#249] opened 2024-02-14 20:01 UTC
### Describe the issue

Sometimes, when looking at a certain type of block (I'm not sure which yet), the game crashes.

### Log output and crash report

https://gist.github.com/unilock/c112c888c32269a959dc8f6c95870c06

### Additional context

I could not upload `debug.log` as it was 55.6 MB in size.

I am aware that I have far too many mods (over 700?) to efficiently diagnose the issue... I'm hoping this is just a missing null check somewhere, before I start a dreadful binary search.

I suspect the issue is related to WTHIT's new "built-in harvestability plugin". Funnily enough, this didn't happen with the previous separate "WTHIT Harvestability" mod (specifically, my fork of it).

**Comment by Sunconure11** [comment] 2024-02-14 21:09
Can confirm the same issue on Quilt.

https://pastebin.com/FUCygCRf

**Comment by MadSciSlack** [comment] 2024-02-14 22:17
I have the same issue, but on Forge.

https://pastebin.com/LfrKLHh4

**Comment by deirn** [comment] 2024-02-14 23:31
It's helpful that there are multiple log files, using the script from [here](https://unix.stackexchange.com/questions/573633/how-can-i-check-if-same-text-appears-in-two-different-files) here are the same mod present:

<details>

```
almostunified
architectury
badpackets
bookshelf
chefsdelight
clumps
connectivity
controlling
create
createdeco
create_dragon_lib
sliceanddice
railways
cupboard
everycomp
farmersdelight
flywheel
frame
framework
kubejs
liquidburner
memoryleakfix
mixinextras
moonlight
mousetweaks
nethersdelight
oceansdelight
byg
patchouli
polymorph
puzzleslib
spectrelib
supermartijn642configlib
supermartijn642corelib
supplementaries
terrablender
wits
wthit
yungsapi
betterdungeons
bettermineshafts
betteroceanmonuments
```
</details>

**Comment by deirn** [comment] 2024-02-15 01:07
Not actually that helpful lol, I can't reproduce with that list.

While it might be fixed with a null check (I'll probably add it regardless), it is sidestepping the issue, some mod seems to be having a `TieredItem` that returns a `null` tier...

Please do check with these versions, I added a debug print that prints the id for every `TieredItem`. It should show what item that has null tier. 
[1.20.1](https://github.com/badasintended/wthit/actions/runs/7909383316/artifacts/1246561469)
[1.19.2](https://github.com/badasintended/wthit/actions/runs/7909395842/artifacts/1246559131)

**Closed as completed** 2024-02-15 01:09 UTC
Labels: bug, neoforge

**Comment by MadSciSlack** [comment] 2024-02-15 09:00
Thanks for a quick response, and for the alt. version to try.  I'm guessing that if the issue is a null tier, then a null check should fix the issue.  I'll respond if there are still issues with the debug version, but otherwise no news is good news and I'll look forward to the formal release.

Cheers,

Slack

**Comment by unilock** [comment] 2024-02-16 13:56
@deirn
> Please do check with these versions, I added a debug print that prints the id for every `TieredItem`. It should show what item that has null tier.

Here's (what I believe to be) the relevant part of `debug.log` with the debug build installed: https://gist.github.com/unilock/6d61b5c574fd07da5d2e44728eca0434

Looks like the problematic `TieredItem` is `techreborn:bronze_pickaxe`. Notably, [Tech Reborn](https://legacy.curseforge.com/minecraft/mc-mods/techreborn) is a Fabric mod that I have running via [Sinytra Connector](https://github.com/Sinytra/Connector). I wonder if that has anything to do with it?

**Comment by deirn** [comment] 2024-02-16 14:10
> Looks like the problematic TieredItem is techreborn:bronze_pickaxe. Notably, [Tech Reborn](https://legacy.curseforge.com/minecraft/mc-mods/techreborn) is a Fabric mod that I have running via [Sinytra Connector](https://github.com/Sinytra/Connector). I wonder if that has anything to do with it?

It might be, on Forge WTHIT uses [`TierSortingRegistry`](https://forge.gemwire.uk/wiki/Making_Tools) to get all the tiers instead of looping through all the items. It makes sense if Fabric tiers are not registered there.
