### ISSUE TITLE
Mining Speed Bug

### ISSUE THREAD

**Issue by Litttlefish** [badasintended/wthit#51] opened 2021-07-03 05:37 UTC
**Describe the bug**
If you installed this mod, the tool's mining speed will drop a lot.
A iron pick works like a wooden one.
Link to log:

**To Reproduce**
Add mod
Craft a Pick
Profit

**Expected behavior**
Everything normal

**Setup**
Do not use Latest
- Minecraft:1.17
- WTHIT:3.6.1
- Fabric Loader:0.11.6
- Fabric API:0.36.0

**Additional context**

**Comment by deirn** [comment] 2021-07-03 07:18
How is this possible? WTHIT doesn't touch anything about mining speed. Can you send your mod list?

**Comment by Litttlefish** [comment] 2021-07-03 07:44
advancementinfo-1.17-fabric0.34.9-1.2.1.jar
AmbientEnvironment-fabric-1.17-rc2-6.0.0.11.jar
anti-night-vision-flash-1.0.0.jar
appleskin-fabric-mc1.17-2.0.0.jar
architectury-2.0.11-fabric.jar
attribute-fix-fabric-1.17-1.0.1.jar
audiooutput-0.0.4.jar
Autofish-0.9.3-fabric-mc1.17.jar
betterbiomeblend-1.17.0-1.1.6-fabric.jar
betterdroppeditems-1.3.0-1.17.jar
blame-1.17-4.0.0-fabric.jar
BowInfinityFix-1.17.x-fabric-rv10.jar
cakechomps-fabric-1.4.0-1.17.jar
cleancut-1.17-4.0-fabric.jar
clear-skies-mc117-1.5.68.jar
cloth-api-2.0.54.jar
cloth-config-5.0.34-fabric.jar
CustomSkinLoader_Fabric-14.13-SNAPSHOT-278.jar
DamageTilt-1.17-fabric-0.1.2.jar
DripSounds-1.17-0.2.1.jar
EntityCulling-Fabric-1.3.0.jar
fabric-api-0.36.0+1.17.jar
ferritecore-3.0.1-fabric.jar
GamemodeOverhaul-1.1.0.jar
InventoryProfilesNext-fabric-1.17-0.8.0.jar
item-model-fix-1.0.2+1.17.jar
krypton-0.1.3.jar
light-fix-1.0.0.jar
mc212-fix-1.0+mc1.17-Fabric.jar
modmenu-2.0.2.jar
notenoughanimations-1.3.0.jar
notenoughcrashes-3.3.1+1.17-fabric.jar
optifabric-1.11.9.jar
physics-mod-1.3.4.1_fabric.jar
preciseblockplacing-1.07+1.17.jar
PresenceFootsteps-r31-1.17-rc1.jar
preview_OptiFine_1.17_HD_U_G9_pre24.jar
RoughlyEnoughItems-6.0.258-alpha-fabric.jar
seamless-loading-screen-1.3.5+1.17.jar
sheepconsistency-1.0.3.jar
shulkerboxtooltip-3.0.0+1.17.jar
sit-1.17-12.jar
smoothboot-fabric-1.16.5-1.6.0.jar
spark-fabric.jar
TRansliterationLib-1.1.0.jar
vectorientation-1.0.1.jar
XaerosWorldMap_1.14.4_Fabric_1.17.jar
Xaeros_Minimap_21.12.3_Fabric_1.17.jar

**Comment by deirn** [comment] 2021-07-03 07:53
Can you try with only WTHIT and Fabric API and see if the issue persist?

**Comment by deirn** [comment] 2021-07-08 09:02
Well alright, tested it myself and can't reproduce it. I'm closing this as invalid.

**Closed by deirn** 2021-07-08 09:02 UTC
Labels: bug, fabric
