### ISSUE TITLE
beetroots error! 

### ISSUE THREAD

**Issue by FourGamingStudio** [badasintended/wthit#211] opened 2023-06-16 11:07 UTC
### Describe the issue

![image](https://github.com/badasintended/wthit/assets/123074279/9d8c840f-ee45-473a-877b-79fb458fba1b)

### Log output and crash report

/execute in minecraft:overworld run tp @s -144.92 64.00 -3376.08 4.14 21.90

**Comment by deirn** [comment] 2023-06-16 11:53
Duplicate of #210

**Closed as not planned by deirn** 2023-06-16 11:53 UTC
Labels: bug, duplicate, fabric
