### ISSUE TITLE
Error on class mcp.mobius.waila.plugin.harvest.provider.HarvestProvider

### ISSUE THREAD

**Issue by zyypj** [badasintended/wthit#307] opened 2024-12-27 01:27 UTC
### Describe the issue

When looking at a block, it gives this error
![image](https://github.com/user-attachments/assets/7920e9ff-19ae-4369-9134-df35880e6097)
in logs:
[22:23:31] [Render thread/ERROR]: [WTHIT] Caught unhandled exception : [class mcp.mobius.waila.plugin.harvest.provider.HarvestProvider] java.lang.IllegalArgumentException: Multiple entries with same key: minecraft:incorrect_for_netherite_tool=mcp.mobius.waila.plugin.harvest.tool.ToolTier@3c18eace and minecraft:incorrect_for_netherite_tool=mcp.mobius.waila.plugin.harvest.tool.ToolTier@7fd1a6bb
[22:23:31] [Render thread/ERROR]: [WTHIT] java.lang.IllegalArgumentException: Multiple entries with same key: minecraft:incorrect_for_netherite_tool=mcp.mobius.waila.plugin.harvest.tool.ToolTier@3c18eace and minecraft:incorrect_for_netherite_tool=mcp.mobius.waila.plugin.harvest.tool.ToolTier@7fd1a6bb
	at knot//com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:382)
	at knot//com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:376)
	at knot//com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:249)
	at knot//com.google.common.collect.RegularImmutableMap.fromEntryArrayCheckingBucketOverflow(RegularImmutableMap.java:136)
	at knot//com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:98)
	at knot//com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:579)
	at knot//com.google.common.collect.ImmutableMap$Builder.buildOrThrow(ImmutableMap.java:607)
	at knot//com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:594)
	at knot//mcp.mobius.waila.plugin.harvest.tool.ToolTier.lambda$resetMap$2(ToolTier.java:67)
	at knot//com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:200)
	at knot//mcp.mobius.waila.plugin.harvest.tool.ToolTier.all(ToolTier.java:72)
	at knot//mcp.mobius.waila.plugin.harvest.provider.HarvestProvider.appendBody(HarvestProvider.java:83)
	at knot//mcp.mobius.waila.gui.hud.ComponentHandler.handleBlock(ComponentHandler.java:73)
	at knot//mcp.mobius.waila.gui.hud.ComponentHandler.gatherBlock(ComponentHandler.java:60)
	at knot//mcp.mobius.waila.gui.hud.TooltipHandler.processTarget(TooltipHandler.java:159)
	at knot//mcp.mobius.waila.gui.hud.TooltipHandler.tick(TooltipHandler.java:86)
	at knot//mcp.mobius.waila.WailaClient.onClientTick(WailaClient.java:67)
	at knot//mcp.mobius.waila.fabric.FabricWailaClient.lambda$onInitializeClient$0(FabricWailaClient.java:22)
	at knot//net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:43)
	at knot//net.minecraft.class_310.handler$bab000$fabric-lifecycle-events-v1$onEndTick(class_310.java:7581)
	at knot//net.minecraft.class_310.method_1574(class_310.java:1940)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1302)
	at knot//net.minecraft.class_310.method_1514(class_310.java:922)
	at knot//net.minecraft.client.main.Main.main(Main.java:267)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

### Log output and crash report

https://gist.github.com/zyypj/6e809dfa3cd05f82d48091f1969cb837

**Comment by zyypj** [comment] 2024-12-27 01:28
crash: https://gist.github.com/zyypj/b5308982fe87bfb36adfa762707faf8b

**Comment by deirn** [comment] 2024-12-27 04:38
Duplicate of #304

**Closed as not planned by deirn** 2024-12-27 04:38 UTC
Labels: bug, fabric
