### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by DuckyCom** [badasintended/wthit#164] opened 2022-09-04 21:51 UTC
### Describe the issue

I tried to use the mod but it seem to crash, i dont know why, i was using it correctly after adding X quantity of mods

### Log output and crash report

https://gist.github.com/DuckyCom/c46e11e3aa2bd62bb49843c0ab2488bb

**Comment by deirn** [comment] 2022-09-04 22:45
Duplicate of #163.

**Closed as not planned by deirn** 2022-09-04 22:45 UTC
Labels: bug, forge
